server:
  port: 8761

eureka:
  client:
    # A eureka server is not a eureka client. It shouldn't register itself.
    register-with-eureka: false
    fetch-registry: false
  server:
    # In a real cluster, you'd turn this on. For a single dev instance, it's simpler to disable.
    wait-time-in-ms-when-sync-empty: 0